# Generated by Django 3.0.2 on 2020-03-08 04:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_info',
            fields=[
                ('usr_id', models.IntegerField(default=21, primary_key=True, serialize=False, unique=True)),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField(default='admin')),
                ('phone', models.IntegerField(default=8888)),
                ('name', models.TextField(default='noname')),
                ('date', models.DateTimeField(verbose_name=datetime.date(2020, 3, 8))),
            ],
        ),
        migrations.CreateModel(
            name='resume_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('univ', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('session', models.TextField()),
                ('ph', models.TextField()),
                ('cph', models.TextField()),
                ('cemail', models.TextField()),
                ('desc', models.TextField()),
                ('cgpa', models.TextField()),
                ('skill_1', models.TextField()),
                ('skill_2', models.TextField()),
                ('skill_3', models.TextField()),
                ('skill_4', models.TextField()),
                ('skill_5', models.TextField()),
                ('skill_6', models.TextField()),
                ('xp_1_title', models.TextField()),
                ('xp_2_title', models.TextField()),
                ('xp_3_title', models.TextField()),
                ('xp_4_title', models.TextField()),
                ('xp_5_title', models.TextField()),
                ('xp_6_title', models.TextField()),
                ('xp_1_desc', models.TextField()),
                ('xp_2_desc', models.TextField()),
                ('xp_3_desc', models.TextField()),
                ('xp_4_desc', models.TextField()),
                ('xp_5_desc', models.TextField()),
                ('xp_6_desc', models.TextField()),
                ('xp_1_session', models.DateField()),
                ('xp_2_session', models.DateField()),
                ('xp_3_session', models.DateField()),
                ('xp_4_session', models.DateField()),
                ('xp_5_session', models.DateField()),
                ('xp_6_session', models.DateField()),
                ('usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.reg_info')),
            ],
        ),
    ]
