# Generated by Django 3.0.2 on 2020-03-09 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.date(2020, 3, 9)),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=18, primary_key=True, serialize=False, unique=True),
        ),
    ]
