# Generated by Django 3.0.2 on 2020-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200309_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=132, primary_key=True, serialize=False, unique=True),
        ),
    ]
