# Generated by Django 3.0.2 on 2020-03-10 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200309_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.date(2020, 3, 10)),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=75, primary_key=True, serialize=False, unique=True),
        ),
    ]
