# Generated by Django 3.0.2 on 2020-03-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200310_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=111, primary_key=True, serialize=False, unique=True),
        ),
    ]
