# Generated by Django 3.0.2 on 2020-03-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20200310_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_info',
            name='date',
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=144, primary_key=True, serialize=False, unique=True),
        ),
    ]
