# Generated by Django 3.0.2 on 2020-03-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_auto_20200311_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=87, primary_key=True, serialize=False, unique=True),
        ),
    ]
