# Generated by Django 3.0.2 on 2020-03-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_auto_20200311_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=75, primary_key=True, serialize=False, unique=True),
        ),
    ]
