# Generated by Django 3.0.2 on 2020-03-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_auto_20200316_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=57, primary_key=True, serialize=False, unique=True),
        ),
    ]
