# Generated by Django 3.0.2 on 2020-03-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_auto_20200316_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_data',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='skill_6',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_1_desc',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_1_session',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_1_title',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_2_desc',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_2_session',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_2_title',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_3_desc',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_3_session',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_3_title',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_4_desc',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_4_session',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_4_title',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_5_desc',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_5_session',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_5_title',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_6_desc',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_6_session',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='xp_6_title',
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
