# Generated by Django 3.0.2 on 2020-03-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_auto_20200318_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_data',
            name='usr_id',
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=114, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resume_data',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.reg_info'),
        ),
    ]
