# Generated by Django 3.0.2 on 2020-03-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0018_auto_20200318_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_data',
            name='cemail',
        ),
        migrations.AlterField(
            model_name='resume_data',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='reg_info',
        ),
    ]
