# Generated by Django 3.0.2 on 2020-03-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_auto_20200323_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume_data',
            old_name='cgpa',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='cph',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='position',
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='session',
        ),
        migrations.AddField(
            model_name='resume_data',
            name='number',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
