# Generated by Django 3.0.2 on 2020-03-26 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_auto_20200326_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_data',
            name='number',
        ),
        migrations.AddField(
            model_name='resume_data',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
