# Generated by Django 3.0.2 on 2020-03-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_auto_20200326_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='resume_data',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
