# Generated by Django 3.0.2 on 2020-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0024_auto_20200402_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='post',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='resume_data',
            name='profession',
            field=models.TextField(default=' '),
        ),
    ]
