# Generated by Django 3.0.2 on 2020-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0025_auto_20200415_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume_data',
            name='profession',
            field=models.TextField(),
        ),
    ]
