# Generated by Django 3.0.2 on 2020-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0027_resume_data_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_data',
            name='profile',
            field=models.TextField(),
        ),
    ]
