# Generated by Django 3.0.2 on 2020-04-18 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0028_auto_20200415_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=50)),
                ('Classs', models.CharField(max_length=50)),
                ('Cgpa', models.FloatField()),
                ('Passing_year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='complete',
            new_name='From',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='post',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='fromm',
            new_name='To',
        ),
        migrations.RenameField(
            model_name='resume_data',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='resume_data',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='resume_data',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='resume_data',
            old_name='profession',
            new_name='Profession',
        ),
        migrations.RenameField(
            model_name='resume_data',
            old_name='profile',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='resume_data',
            old_name='univ',
            new_name='University',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skills',
            new_name='Skills',
        ),
        migrations.AddField(
            model_name='resume_data',
            name='FullName',
            field=models.CharField(default='rumna', max_length=50),
        ),
        migrations.DeleteModel(
            name='schooling',
        ),
    ]
