# Generated by Django 3.0.2 on 2020-04-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0029_auto_20200418_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_data',
            name='FullName',
            field=models.CharField(max_length=50),
        ),
    ]
