# Generated by Django 3.0.2 on 2020-04-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0030_auto_20200419_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Classs',
            new_name='Class',
        ),
    ]
